
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Store these values in your deployment environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://qjeyvwvydtcckijaxpap.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZXl2d3Z5ZHRjY2tpamF4cGFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDE4NjIsImV4cCI6MjA2MTE3Nzg2Mn0.M5FukVqFpzXI1gNhVy6F8EFyW69cqlrHh8cqiOadr2o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
